- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Provision instances
    ec2:
      instance_type: "{{ insttype }}"
      instance_tags: {"{{ tagKey }}":"{{ tagVal }}"}
      image: "{{ instami }}"
      count: "{{ instcount }}"
      group_id: "{{ instsg }}"
      region: ap-northeast-1
